kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/jenkins_home"
